config/routes.rb
Rails.application.routes.draw do
  root to: 'kalendar#home'

  # User Registration
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # User Authentication
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # User Settings
  resources :users
  get '/users/:id/tasks', to: 'tasks#show'

  # Task Creation
  get  '/tasks', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  delete '/tasks', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  validates :name, presence: true
  validates :name, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :user_id, presence: true
  validates :group_id, presence: true
  validates_uniqueness_of :user_id, scope: :group_id
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 40 }
  validates :description, length: { maximum: 255 }
  validates :start_at, presence: true
  validates :finish_at, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :members
  has_many :groups, through: :members

  before_save :downcase_email

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def joined_group_members
    user_ids = Member.where(group_id: group_ids).distinct.pluck(:user_id)
    User.where(id: user_ids).where.not(id: id)
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def redirect_unless_logged_in
    redirect_to login_path, flash: { danger: 'Please log in.' } unless logged_in?
  end

  def redirect_if_logged_in
    redirect_to root_path, flash: { danger: 'You are already logged in.' } if logged_in?
  end
end

app/controllers/kalendar_controller.rb
class KalendarController < ApplicationController
  before_action :redirect_unless_logged_in

  def home
    @tasks = current_user.tasks
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      redirect_to root_path, flash: { success: 'Logged in successfully.' }
    else
      redirect_to login_path, flash: { danger: 'Invalid email/password combination.' }
    end
  end

  def destroy
    log_out
    redirect_to login_path, flash: { success: 'Logged out successfully.' }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :redirect_unless_logged_in

  protect_from_forgery except: :create

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to root_path, flash: { success: 'Your task has been successfully created :)' }
    else
      render 'new'
    end
  end

  def edit; end

  def show; end

  def update; end

  def destroy
    task = Task.find_by(id: params[:id])
    task.destroy
    redirect_to root_path, flash: { success: 'Task deleted' }
  end

  private

  def task_params
    params.require(:task).permit(
      :title,
      :start_at,
      :finish_at,
      :description
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_unless_logged_in, only: [:show]
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    if is_current_user?(@user)
      @tasks = @user.tasks.first(5)
    else
      redirect_to root_path, flash: { danger: '閲覧権限がありません。原則、他のユーザーのプロフィール情報は閲覧することができません。' }
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user, flash: { success: 'Your account has been successfully created.' }
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def is_current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/kalendar/home.html.erb
<div id="modal-tasks-description" class="container" v-cloak>
  <%= month_calendar(attribute: :start_at, end_attribute: :end_at, events: @tasks) do |date, tasks| %>
    <%= date.day %>
    <% if tasks.present? %>
      <a @click="openModal(<%= date.day %>)">
        <%= tasks.count %>件予定があります
      </a>
      <b-modal :active.sync="isCardModalActive[<%= date.day %>]" :width="640" scroll="keep">
        <div class="card">
          <div class="card-content">
            <div class="content">
              <% tasks.each_with_index do |task, index| %>
                <p>
                  Title: <%= task.title %>
                </p>
                <p>
                  Description:
                  <%= task.description %>
                </p>
                <small>
                  <%= task.start_at %>
                  <%= task.finish_at %>
                </small>
                <br />
                <% if (current_user == task.user) %>
                  <%= link_to "delete", "/tasks?id=#{task.id}", method: :delete, data: { confirm: "You sure?" } %>
                <% end %>
                <% unless index == tasks.size-1 %>
                  <hr>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </b-modal>
    <% end %>
  <% end %>
</div>


<%= javascript_pack_tag 'modal-tasks-description' %>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <% if logged_in? %>
      <a class="navbar-item is-size-3" href="/">
        <span>Kalendar</span>
      </a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    <% else %>
      <a class="navbar-item is-size-3" href="/login">
        <span>Kalendar</span>
      </a>
    <% end %>
  </div>

  <div id="navbar" class="navbar-menu">
    <% if logged_in?  %>
      <div class="navbar-end">
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Accounts</a>
          <div class="navbar-dropdown">
            <%= link_to 'Settings', current_user, class: 'navbar-item' %>
            <%= link_to 'Log out', logout_path, method: :delete, class: 'navbar-item' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <article class="message is-<%= message_type %> notification">
        <div class="message-body">
          <%= message %>
        </div>
      </article>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.present? %>
  <article class="message is-danger">
    <div class="message-header">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <div class="message-body">
      <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </article>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="new-task has-text-left" style="margin-left: 5rem">
    <a href="/tasks" class="button create-button is-rounded is-large">
      <i class="fas fa-plus"></i>New Task!!
    </a>
  </div>
  <div class="calendar-heading is-size-3 columns">
    <%= link_to t('simple_calendar.previous', default: '◀︎'), calendar.url_for_previous_view, class: 'column is-one-fifth' %>
    <span class="calendar-title column has-text-centered"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '▶︎'), calendar.url_for_next_view, class: 'column has-text-right is-one-fifth' %>
  </div>

  <table class="table is-bordered is-fullwidth">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class="has-text-centered"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% block.call day, sorted_events.fetch(day, []) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/new.html.erb
<div class="task-creation-fields">
  <h1 class="has-text-centered is-size-3">Create Task</h1>
  <%= form_with( model: @task, local: true, url: tasks_path ) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title, class: 'label' %>
    <%= f.text_field :title, class: 'input' %>

    <%= f.label :start_at, class: 'label' %>
    <%= f.datetime_field :start_at, class: 'input' %>

    <%= f.label :finish_at, class: 'label' %>
    <%= f.datetime_field :finish_at, class: 'input' %>

    <%= f.label :description, class: 'label' %>
    <%= f.text_area :description, class: 'textarea' %>

    <%= f.submit "Save", class: "button is-info" %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: yield(:post_path)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name, class: 'label' %>
  <%= f.text_field :name, class: 'input', placeholder: 'example user' %>

  <%= f.label :email, class: 'label'  %>
  <%= f.email_field :email, class: 'input', placeholder: 'e.g example@example.com' %>

  <%= f.label :password, class: 'label'  %>
  <%= f.password_field :password, class: 'input' %>

  <%= f.label :password_confirmation, class: 'label'  %>
  <%= f.password_field :password_confirmation, class: 'input' %>

  <%= f.submit 'Sign Up', class: "button is-info" %>
<% end %>

app/views/users/new.html.erb
<% provide(:post_path, signup_path) %>
<div class="registration-fields">
  <h1 class="has-text-centered is-size-3">Sign Up</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="profile columns">
  <div class="user-info has-text-centered column is-one-third">
    <h1 class="is-size-3">Profile</h1>
    <div class="users-image">
      <% image_path = Faker::Avatar.image %>
      <img src="<%= "#{image_path}" %>">
    </div>
    <div class="users-name is-size-4">
      <span><%= @user.name %></span>
    </div>
    <div class="users-email is-size-4">
      <span><%= @user.email %></span>
    </div>
    <div class="new-task has-text-centered">
      <a href="/tasks" class="button create-button is-rounded is-large">
        <i class="fas fa-plus"></i>New Task!!
      </a>
    </div>
  </div>
  <div class="users-tasks column">
      <div class="card">
        <header class="card-header">
          <div class="card-header-title is-3">
            Tasks
          </div>
        </header>
        <div class="card-content">
          <div class="content">
            <% if @tasks.present? %>
              <% @tasks.each do |task| %>
                <!-- TODO href: <タスクの詳細ページ get '/users/:id/tasks/:id', to: 'tasks#edit -->
                <%= link_to task.title %>
                <br>
                <%= task.description %>
                <br>
                start_at: <%= task.start_at %>
                finish_at: <%= task.finish_at %>
                <hr>
              <% end %>
              <div class="to-more-task-link has-text-right">
                <!-- TODO href: <タスク一覧のページ get '/users/:id/tasks', to: 'tasks#show' -->
                <%= link_to 'Show more ...' %>
              </div>
            <% else %>
              <div class="message is-info">
                <div class="message-header">
                  タスクがまだ作成されていません
                </div>
                <div class="message-body">
                  タスクを登録すると、その日の自分の予定や、グループメンバーの予定が一覧で確認できます。
                  <hr>
                  メールアドレス下の <u>[ New Task ]</u>から、さっそく新しいタスクを作成してみましょう！
              </div>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>